### PR TITLE
Add algolia indexing capabilities

### PR DESCRIPTION
**Pull request by redox**
Add a simple `algoliasearch`-based concern indexing big articles in
multiple smaller records.

Note: for the sake of the MVP, the split function is currently very stupid.

### CODE REVIEW

**Comment by hannesfostie** [comment]
This is great @redox ! Certainly something I can work with.

I'll port this over to our app some time next week and keep you posted if I run into any issues or questions.

**Comment by redox** [comment]
Awesome @hannesfostie!

I would recommend reading https://blog.algolia.com/how-to-build-a-helpful-search-for-technical-documentation-the-laravel-example/ in order to understand how our [DocSearch](https://community.algolia.com/docsearch/) crawler is building the Algolia records splitting documentation pages in multiple objects with title hierarchy.

Let us know if that makes sense, we would love to help!

**Comment by hannesfostie** [comment]
@redox while I'm working on porting your PR over to our app and filling in the missing pieces, I've found 2 bits of feedback I wanted to share and get your thoughts on:

- The [webmock library](https://www.algolia.com/doc/api-client/ruby/mocking/) that you provide does not work quite like "advertised" in that api client article. I've tried a number of things, required the file in different places, but no matter what I tried the stubs weren't being loaded. I ended up copy and pasting all those stubs into our test config
- The above library doesn't correctly stub all requests. The way you're deleting all records for an Article object (`delete_by_query`) causes an infinite loop [because of this code](https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/index.rb#L409-L414) and the way the stubs are set up - the stub should return `hits` in the body I imagine to prevent this.

**Comment by redox** [comment]
> The webmock library that you provide does not work quite like "advertised" in that api client article. I've tried a number of things, required the file in different places, but no matter what I tried the stubs weren't being loaded. I ended up copy and pasting all those stubs into our test config

Oh that's weird; just including the file & calling `WebMock.enable!` should make it :/

> The above library doesn't correctly stub all requests. The way you're deleting all records for an Article object (delete_by_query) causes an infinite loop because of this code and the way the stubs are set up - the stub should return hits in the body I imagine to prevent this.

Arg, that's correct -> will add a GH issue.

**Comment by redox** [comment]
Just released the `1.15.0` version that will fix the `delete_by_query`.

**Comment by hannesfostie** [comment]
Thanks @redox ! That was incredibly fast :-) The previously failing tests now seem to work.

As for the webmock issue, I'm going to try to replicate in this repo after merging this PR.

**Comment by redox** [comment]
> Thanks @redox ! That was incredibly fast :-) The previously failing tests now seem to work.

You're welcome! Maybe force usage of `1.15.1`, there was a small perf regression in `1.15.0`.

**Comment by hannesfostie** [comment]
@redox is it possible that version has not been released? It can't be found on Rubygems

**Comment by redox** [comment]
> @redox is it possible that version has not been released? It can't be found on Rubygems

Arg /o\ should be good now /o\ @hannesfostie

**Pull request merged**
